apiVersion: v1
kind: Service
metadata:
  labels:
    app: zbx-web-mysql
  name: zbx-web-mysql-service
spec:
  selector:
    app: zbx-web-mysql
  type: NodePort  
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080